import React, { Component } from 'react';
import './index.css';

class Content extends Component {
  render() {
    return (
      <div id = "Content" >
        <p>Fake text generated by https://lipsum.sugutsukaeru.jp。</p>
        <p>私は時間どうもこんな発見顔ってのの時にかかるんん。</p>

        <p>どうも場合の忠告者はよしその謝罪たんかもがしてみるたよりは学習聞いたたて、
        少しにも気に入るでないですあり。</p>

        <p>威力からしう者もどうも今でよくだたなけれ。</p>

        <p>一々三宅さんから自覚先生わざわざ攻撃が経るべき中学この人そこか料簡のというご解剖ですですですですと、
        この当時はこれか願会員とするて、
        岡田君ののを雑木の私におもに大話と蒙りてあいつ主意がご開始があてるようにとうとう皆仕事にするですなけれと、
        ぼんやりついに注文にしなば来ないのがなるませで。</p>

        <p>しかしだから大自分がし気はそれほど自由と構わだで、
        そんな規律へはいありとという監獄にありてならでべき。</p>
      </div>
    );
  }
}

export default Content;
